#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f f1_fsm_1s.vcd

# run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace f1_fsm_1s.sv --exe f1_fsm_1s_tb.cpp

# build c++ progect via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_fsm_1s.mk Vf1_fsm_1s

# run executable simulation file
obj_dir/Vf1_fsm_1s