#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f fullF1Light.vcd

# run verilator to translate verilog into c++, including c++ testbench
verilator -Wall --cc --trace fullF1Light.sv --exe fullF1Light_tb.cpp

# build c++ progect via make automatically generated by Verilator
make -j -C obj_dir/ -f VfullF1Light.mk VfullF1Light

# run executable simulation file
obj_dir/VfullF1Light